id: AEC38C4A4
base_file: f469A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:40:26.820870
  last_modified_at: 2022-05-30 20:40:26.820877
