id: AEC38C4A4
base_file: fDCF4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:40:26.827000
  last_modified_at: 2022-05-30 20:40:26.827005
